# Used for SPAs to handle the routing internally
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set the headers for security
[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Setting an empty value ensures that they aren't used
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      fullscreen=*
    """
